### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by Babaevzhu** [ZJUYH/grid_map_yh#1]
When I catkin_make the project it reports some errors but I can't find what's wrong with it. Here is the error detail, please give me some help, Thanks you very much:

/home/catkin_ws/src/grid_map_yh/src/laserToMap.cpp: In constructor ‘gridMapping::gridMapping(ros::NodeHandle&)’:
/home/ame/robot_ws/src/grid_map_yh/src/laserToMap.cpp:102:59: error: no matching function for call to ‘std::unique_ptr<PointMatcher<float>::Transformation>::unique_ptr(std::shared_ptr<PointMatcher<float>::Transformation>)’
     groundTolarance(getParam<double>("groundTolarance", 0))
                                                           ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from /usr/include/boost/math/policies/error_handling.hpp:12,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/kinetic/include/ros/time.h:58,
                 from /opt/ros/kinetic/include/ros/ros.h:38,
                 from /home/robot_ws/src/grid_map_yh/src/laserToMap.cpp:1:
/usr/include/c++/5/bits/unique_ptr.h:228:2: note: candidate: template<class _Up, class> std::unique_ptr<_Tp, _Dp>::unique_ptr(std::auto_ptr<_Up>&&)
  unique_ptr(auto_ptr<_Up>&& __u) noexcept;

**Comment by HuanYin94** [comment]
> When I catkin_make the project it reports some errors but I can't find what's wrong with it. Here is the error detail, please give me some help, Thanks you very much:
> 
> /home/catkin_ws/src/grid_map_yh/src/laserToMap.cpp: In constructor ‘gridMapping::gridMapping(ros::NodeHandle&)’:
> /home/ame/robot_ws/src/grid_map_yh/src/laserToMap.cpp:102:59: error: no matching function for call to ‘std::unique_ptr<PointMatcher::Transformation>::unique_ptr(std::shared_ptr<PointMatcher::Transformation>)’
> groundTolarance(getParam("groundTolarance", 0))
> ^
> In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
> from /usr/include/c++/5/locale:43,
> from /usr/include/c++/5/iomanip:43,
> from /usr/include/boost/math/policies/error_handling.hpp:12,
> from /usr/include/boost/math/special_functions/round.hpp:14,
> from /opt/ros/kinetic/include/ros/time.h:58,
> from /opt/ros/kinetic/include/ros/ros.h:38,
> from /home/robot_ws/src/grid_map_yh/src/laserToMap.cpp:1:
> /usr/include/c++/5/bits/unique_ptr.h:228:2: note: candidate: template<class _Up, class> std::unique_ptr<_Tp, _Dp>::unique_ptr(std::auto_ptr<_Up>&&)
> unique_ptr(auto_ptr<_Up>&& __u) noexcept;

Have you installed libpointmatcher and relevant libs ?

**Comment by Babaevzhu** [comment]
I have find the issue. The error is appeared when I used the latest version of libpointmatcher. When I use the old version libpointmatcher, it works well. thanks yor your replying.
