### ISSUE TITLE
路径规划问题

### ISSUE THREAD

**Issue by Jessie37464** [ZJUYH/grid_map_yh#4]
您好,我想问一下,您的这个路径规划和建立好的高程图要怎么结合呢?

**Comment by HuanYin94** [comment]
> 您好,我想问一下,您的这个路径规划和建立好的高程图要怎么结合呢?

你好，代码比较久远，细节忘得差不多了。。。应该是高程图生成占用栅格地图，A*在栅格地图上规划。

**Comment by Jessie37464** [comment]
您好,那是直接运行路径规划代码吗?还是说把要把路径规划部分的代码移植进ros的路径规划框架中呢?

**Comment by HuanYin94** [comment]
> 您好,那是直接运行路径规划代码吗?还是说把要把路径规划部分的代码移植进ros的路径规划框架中呢?

自己写的A*，直接运行就可以，不需要ros框架

**Comment by Jessie37464** [comment]
您好,接着是路径规划生成路径点,并发布速度指令让机器人进行路径跟踪?

**Comment by HuanYin94** [comment]
> 您好,接着是路径规划生成路径点,并发布速度指令让机器人进行路径跟踪?

这份代码只生成路径，没有包含后续的速度指令规划。

**Comment by Jessie37464** [comment]
好的,太感谢您了!!!
