### ISSUE TITLE
高程图生成占用栅格地图

### ISSUE THREAD

**Issue by Jessie37464** [ZJUYH/grid_map_yh#5]
您好，您生成的占用栅格地图是什么样的呢？该栅格地图是只包含0和1吗？

**Comment by HuanYin94** [comment]
> 您好，您生成的占用栅格地图是什么样的呢？该栅格地图是只包含0和1吗？

是的，occupy 或 free

**Comment by HuanYin94** [comment]
> 您好，您生成的占用栅格地图是什么样的呢？该栅格地图是只包含0和1吗？

具体实现忘得差不多了，细节请看traversalCheck.cpp的实现，cpp会对栅格能否同行有判断

**Comment by Jessie37464** [comment]
您好,请问您有对应的文献参考吗?
还有就是如果路径都可通行,但是要找到一条地形代价最低的路径,这样的情况,也可以按照您说的方法吗?

**Comment by HuanYin94** [comment]
> 您好,请问您有对应的文献参考吗?
> 还有就是如果路径都可通行,但是要找到一条地形代价最低的路径,这样的情况,也可以按照您说的方法吗?

参考文献：
Navigation planning for legged robots in challenging terrain

很多路径找最低cost路径的话，我的想法是工程实现可以遍历所有路径然后求个最小，但这样效率估计比较低。
当然，其他rrt等方法也可以试试，不一定用A*

**Comment by Jessie37464** [comment]
> > 您好,请问您有对应的文献参考吗?
> > 还有就是如果路径都可通行,但是要找到一条地形代价最低的路径,这样的情况,也可以按照您说的方法吗?
> 
> 参考文献：
> Navigation planning for legged robots in challenging terrain
> 
> 很多路径找最低cost路径的话，我的想法是工程实现可以遍历所有路径然后求个最小，但这样效率估计比较低。
> 当然，其他rrt等方法也可以试试，不一定用A*

**Comment by Jessie37464** [comment]
感谢您提供的文献和建议!!!
看了您的代码traversalCheck.cpp,最后发布了两个topic(grid_map_travelChecked和occuMap).
1.发布grid_map_travelChecked主题,是为展示可通行图;
2.发布occuMap是为了路径规划.
请问我这样理解对吗?

**Comment by HuanYin94** [comment]
> 感谢您提供的文献和建议!!!
> 看了您的代码traversalCheck.cpp,最后发布了两个topic(grid_map_travelChecked和occuMap).
> 1.发布grid_map_travelChecked主题,是为展示可通行图;
> 2.发布occuMap是为了路径规划.
> 请问我这样理解对吗?

correct

**Comment by Jessie37464** [comment]
> > 感谢您提供的文献和建议!!!
> > 看了您的代码traversalCheck.cpp,最后发布了两个topic(grid_map_travelChecked和occuMap).
> > 1.发布grid_map_travelChecked主题,是为展示可通行图;
> > 2.发布occuMap是为了路径规划.
> > 请问我这样理解对吗?
> 
> correct

好的,太感谢您了!
