### ISSUE TITLE
高程图

### ISSUE THREAD

**Issue by Jessie37464** [ZJUYH/grid_map_yh#6]
您好,我用[https://github.com/ANYbotics/elevation_mapping]建立的高程图生成了地图,并保存为elevation.bag.
请问使用traversalCheck.launch前,是不是要先把elevation.bag转化为grid_map,您是怎么转化的呢?

**Comment by HuanYin94** [comment]
> 您好,我用[https://github.com/ANYbotics/elevation_mapping]建立的高程图生成了地图,并保存为elevation.bag.
> 请问使用traversalCheck.launch前,是不是要先把elevation.bag转化为grid_map,您是怎么转化的呢?

不太明白你的问题，是将rosbag转换为grid map？
我是将激光点云转换为gridmap输入traversalCheck的

**Comment by Jessie37464** [comment]
> > 您好,我用[https://github.com/ANYbotics/elevation_mapping]建立的高程图生成了地图,并保存为elevation.bag.
> > 请问使用traversalCheck.launch前,是不是要先把elevation.bag转化为grid_map,您是怎么转化的呢?
> 
> 不太明白你的问题，是将rosbag转换为grid map？
> 我是将激光点云转换为gridmap输入traversalCheck的

学会了,太感谢您了!
