### ISSUE TITLE
path_planning_demo.cpp

### ISSUE THREAD

**Issue by Jessie37464** [ZJUYH/grid_map_yh#7]
您好,我想问一下在path_planning_demo.cpp中,位置为什么要这么处理呢?
        pose.pose.position.x = (path.at(i).y - mapSize/2)*resolution;
        pose.pose.position.y = (mapSize/2 - path.at(i).x)*resolution;
是跟坐标系有关系吗?

**Comment by HuanYin94** [comment]
> 您好,我想问一下在path_planning_demo.cpp中,位置为什么要这么处理呢?
> pose.pose.position.x = (path.at(i).y - mapSize/2)*resolution;
> pose.pose.position.y = (mapSize/2 - path.at(i).x)*resolution;
> 是跟坐标系有关系吗?

应该是根据grid的x/y求metric的位姿x/y

**Comment by Jessie37464** [comment]
请问这里的grid和metric分别是什么的?

**Comment by HuanYin94** [comment]
> 请问这里的grid和metric分别是什么的?

抽象栅格 to 真实坐标，需要乘分辨率

**Comment by Jessie37464** [comment]
请问,他这个的坐标是距离目标点的坐标吗?我把路径点的坐标进行输出,然后最后一个点是(0,0)?
请问是这样理解的吗?

**Comment by Jessie37464** [comment]
是不是因为,这个地图是以机器人为中心,所以最后一个点是(0,0)呢

**Comment by HuanYin94** [comment]
> 请问,他这个的坐标是距离目标点的坐标吗?我把路径点的坐标进行输出,然后最后一个点是(0,0)?
> 请问是这样理解的吗?

细节我真的忘了...

**Comment by HuanYin94** [comment]
> 是不是因为,这个地图是以机器人为中心,所以最后一个点是(0,0)呢

显而易见，localmap 肯定是以机器人自己为中心啊

**Comment by Jessie37464** [comment]
好的,感谢您,思路更清晰了!
