### ISSUE TITLE
路径跟踪问题

### ISSUE THREAD

**Issue by Jessie37464** [ZJUYH/grid_map_yh#8]
您好,我想问一下,给定规划的路径后,您是如何让机器人跟踪路径的呢,用的是哪个ros包呢?

**Comment by ZJUYH** [comment]
后面不是我负责的了

**Comment by HuanYin94** [comment]
> 您好,我想问一下,给定规划的路径后,您是如何让机器人跟踪路径的呢,用的是哪个ros包呢?

你自己花点力气研究吧，后面不是我负责的了
